/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Apuesta.*;
import ManejoArchivos.ManejoArchivo;
import Reportes.Reportes;
import javax.swing.JOptionPane;


/**
 *
 * @author GORDILLO G
 */
public class CargarApuestas extends javax.swing.JFrame {

    /**
     * Creates new form cargarApuestas
     */
    String t = "Nombre,Monto Apostado,Posicion 1 apostada,Posicion 2 apostada, Posicion3 apostada, Posicion 4 apostada, Posicion 5 apostada,Posicion 6 apostada,Posicion 7 apostada,Posicion 8 apostada,Posicion 9 apostada,Posicion 10 apostada\n";
    Reportes reporte = new Reportes();
    Apuesta[] apuesta;
    String errores;
    int contador;
            
    public CargarApuestas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cerrarApuesta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload (1).png"))); // NOI18N
        jButton1.setText("Cargar apuestas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 240, 210, 50);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Dubai", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cargar las apuestas realizadas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 320, 42);

        cerrarApuesta.setBackground(new java.awt.Color(0, 0, 0));
        cerrarApuesta.setFont(new java.awt.Font("Dubai", 3, 18)); // NOI18N
        cerrarApuesta.setForeground(new java.awt.Color(0, 0, 0));
        cerrarApuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel (1).png"))); // NOI18N
        cerrarApuesta.setText("Cerrar apuestas");
        cerrarApuesta.setBorder(null);
        cerrarApuesta.setBorderPainted(false);
        cerrarApuesta.setContentAreaFilled(false);
        cerrarApuesta.setFocusPainted(false);
        cerrarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarApuestaActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarApuesta);
        cerrarApuesta.setBounds(30, 310, 200, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apuestas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         try{
             
         
            // Carga de las apuestas
        ManejoArchivo cargar = new ManejoArchivo();
        cargar.leerLinea();
        apuesta = cargar.getApuestas();
        contador = cargar.getContador();
        errores = cargar.getErrores();
        
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"No se selecciono ningun archivo");
        }
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarApuestaActionPerformed
        //Se verifican las apuestas cargas
        VerificarApuestas ver2 = new VerificarApuestas();
        Apuesta[] corregidas =ver2.verficadorApuestas(apuesta, contador,errores,t);
        Apuesta[] correctas =ver2.correctas(corregidas);
        Reportes reporte1 = ver2.actualizarReporte(reporte);
        
                
        //Se les da seguimiento a las apuestas correctas       
        IngresarPosiciones posiciones = new IngresarPosiciones(correctas,reporte1);
        this.setVisible(false);
        posiciones.setVisible(true);
    }//GEN-LAST:event_cerrarApuestaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarApuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
