/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Apuesta.*;
import ManejoArchivos.ManejoArchivo;
import Reportes.Reportes;
import javax.swing.JOptionPane;


/**
 *
 * @author GORDILLO G
 */
public class CargarApuestas extends javax.swing.JFrame {

    /**
     * Creates new form cargarApuestas
     */
    String t = "Nombre,Monto Apostado,Posicion 1 apostada,Posicion 2 apostada, Posicion3 apostada, Posicion 4 apostada, Posicion 5 apostada,Posicion 6 apostada,Posicion 7 apostada,Posicion 8 apostada,Posicion 9 apostada,Posicion 10 apostada\n";
    Reportes reporte = new Reportes();
    Apuesta[] apuesta;
    String errores;
    int contador;
            
    public CargarApuestas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cerrarApuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButton1.setText("Cargar apuestas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setText("Cargar las apuestas realizadas");

        cerrarApuesta.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        cerrarApuesta.setText("Cerrar apuestas");
        cerrarApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarApuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrarApuesta)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(cerrarApuesta)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         try{
             
         
            // Carga de las apuestas
        ManejoArchivo cargar = new ManejoArchivo();
        cargar.leerLinea();
        apuesta = cargar.getApuestas();
        contador = cargar.getContador();
        errores = cargar.getErrores();
        
        
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"No se selecciono ningun archivo");
        }
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrarApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarApuestaActionPerformed
        //Se verifican las apuestas cargas
        VerificarApuestas ver2 = new VerificarApuestas();
        Apuesta[] corregidas =ver2.verficadorApuestas(apuesta, contador,errores,t);
        Apuesta[] correctas =ver2.correctas(corregidas);
        Reportes reporte1 = ver2.actualizarReporte(reporte);
        
                
        //Se les da seguimiento a las apuestas correctas       
        IngresarPosiciones posiciones = new IngresarPosiciones(correctas,reporte1);
        this.setVisible(false);
        posiciones.setVisible(true);
    }//GEN-LAST:event_cerrarApuestaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarApuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
